function otraFuncion(){
      seRompe()
}
function seRompe(){
      return 3 + z 
}
try{
      otraFuncion()
}catch(err){
      console.error('algo se rompio')
      console.error(err.message)
}
console.log('esto esta despues de try')